#!/usr/bin/env python3
import sys
import os


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>", file=sys.stderr)
        exit(1)
    if not os.path.isfile(sys.argv[1]):
        print(f"factors: File {sys.argv[1]} not found", file=sys.stderr)
        exit(1)

    with open(sys.argv[1]) as f:
        for i in f:
            i = int(i)
            if i % 2 == 0:
                print(f"{i}={i // 2}*2")
                continue

            div = rho(i, 1)
            print(f"{i}={i // div}*{div}")


def rho(n, c):
    t = 2
    h = 2
    d = 1

    while d == 1:
        t = ((t ** 2) + c) % n
        h = ((h ** 2) + c) % n
        h = ((h ** 2) + c) % n
        d = gcd(t - h, n)

    if d == n:
        return rho(n, c + 1)
    return d


def gcd(a, b):
    if(b == 0):
        return a
    else:
        return gcd(b, a % b)


if __name__ == '__main__':
    main()
